name: github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: create/update ticket
        run: sh ./sh/newTicket.sh
        env:
          OAuth: ${{ secrets.OAuth }}
          XOrgId: ${{ secrets.XOrgId }}

      - name: run tests
        run: sh ./sh/tests.sh
        env:
          OAuth: ${{ secrets.OAuth }}
          XOrgId: ${{ secrets.XOrgId }}

      - name: docker
        run: sh ./sh/docker.sh
        env:
          OAuth: ${{ secrets.OAuth }}
          XOrgId: ${{ secrets.XOrgId }}
